// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LMS.Util.Email_Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\Siddhartha\CrowdSourcedAppraisalProcess\Development\LMS\LMS.Util\Email Templates\testing.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class testing : testingBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\n<!DOCTYPE> \r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n</head>\r\n<bod" +
                    "y>\r\n    LEAVE APPLIED\r\n    <table>\r\n        <tr>\r\n            <td><b>Name :</b><" +
                    "/td>\r\n            <td>");
            
            #line 25 "F:\Siddhartha\CrowdSourcedAppraisalProcess\Development\LMS\LMS.Util\Email Templates\testing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        </tr>\r\n        <tr>\r\n            <td><b>Designation :</b></td>\r\n  " +
                    "          <td>");
            
            #line 29 "F:\Siddhartha\CrowdSourcedAppraisalProcess\Development\LMS\LMS.Util\Email Templates\testing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Designation));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        </tr>\r\n        <tr>\r\n            <td><b>Contact Number :</b></td>\r" +
                    "\n            <td>");
            
            #line 33 "F:\Siddhartha\CrowdSourcedAppraisalProcess\Development\LMS\LMS.Util\Email Templates\testing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ContactNumber));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        </tr>\r\n\t\t<tr>\r\n            <td><b>Type :</b></td>\r\n            <td" +
                    ">");
            
            #line 37 "F:\Siddhartha\CrowdSourcedAppraisalProcess\Development\LMS\LMS.Util\Email Templates\testing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        </tr>\r\n\t\t<tr>\r\n            <td><b>Unit :</b></td>\r\n            <td" +
                    ">");
            
            #line 41 "F:\Siddhartha\CrowdSourcedAppraisalProcess\Development\LMS\LMS.Util\Email Templates\testing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Unit));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        </tr>\r\n        <tr>\r\n            <td><b>From :</b></td>\r\n         " +
                    "   <td>");
            
            #line 45 "F:\Siddhartha\CrowdSourcedAppraisalProcess\Development\LMS\LMS.Util\Email Templates\testing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StartDate));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        </tr>\r\n        <tr>\r\n            <td><b>To :</b></td>\r\n           " +
                    " <td>");
            
            #line 49 "F:\Siddhartha\CrowdSourcedAppraisalProcess\Development\LMS\LMS.Util\Email Templates\testing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EndDate));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        </tr>\r\n        <tr>\r\n            <td><b>Applied On :</b></td>\r\n   " +
                    "         <td>");
            
            #line 53 "F:\Siddhartha\CrowdSourcedAppraisalProcess\Development\LMS\LMS.Util\Email Templates\testing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreatedOn));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        </tr>\r\n    </table>\r\n\r\n\r\n</body>\r\n</html>");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "F:\Siddhartha\CrowdSourcedAppraisalProcess\Development\LMS\LMS.Util\Email Templates\testing.tt"

private string _NameField;

/// <summary>
/// Access the Name parameter of the template.
/// </summary>
private string Name
{
    get
    {
        return this._NameField;
    }
}

private string _DesignationField;

/// <summary>
/// Access the Designation parameter of the template.
/// </summary>
private string Designation
{
    get
    {
        return this._DesignationField;
    }
}

private string _ContactNumberField;

/// <summary>
/// Access the ContactNumber parameter of the template.
/// </summary>
private string ContactNumber
{
    get
    {
        return this._ContactNumberField;
    }
}

private string _TypeField;

/// <summary>
/// Access the Type parameter of the template.
/// </summary>
private string Type
{
    get
    {
        return this._TypeField;
    }
}

private string _UnitField;

/// <summary>
/// Access the Unit parameter of the template.
/// </summary>
private string Unit
{
    get
    {
        return this._UnitField;
    }
}

private string _StartDateField;

/// <summary>
/// Access the StartDate parameter of the template.
/// </summary>
private string StartDate
{
    get
    {
        return this._StartDateField;
    }
}

private string _EndDateField;

/// <summary>
/// Access the EndDate parameter of the template.
/// </summary>
private string EndDate
{
    get
    {
        return this._EndDateField;
    }
}

private string _CreatedOnField;

/// <summary>
/// Access the CreatedOn parameter of the template.
/// </summary>
private string CreatedOn
{
    get
    {
        return this._CreatedOnField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool NameValueAcquired = false;
if (this.Session.ContainsKey("Name"))
{
    this._NameField = ((string)(this.Session["Name"]));
    NameValueAcquired = true;
}
if ((NameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Name");
    if ((data != null))
    {
        this._NameField = ((string)(data));
    }
}
bool DesignationValueAcquired = false;
if (this.Session.ContainsKey("Designation"))
{
    this._DesignationField = ((string)(this.Session["Designation"]));
    DesignationValueAcquired = true;
}
if ((DesignationValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Designation");
    if ((data != null))
    {
        this._DesignationField = ((string)(data));
    }
}
bool ContactNumberValueAcquired = false;
if (this.Session.ContainsKey("ContactNumber"))
{
    this._ContactNumberField = ((string)(this.Session["ContactNumber"]));
    ContactNumberValueAcquired = true;
}
if ((ContactNumberValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ContactNumber");
    if ((data != null))
    {
        this._ContactNumberField = ((string)(data));
    }
}
bool TypeValueAcquired = false;
if (this.Session.ContainsKey("Type"))
{
    this._TypeField = ((string)(this.Session["Type"]));
    TypeValueAcquired = true;
}
if ((TypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Type");
    if ((data != null))
    {
        this._TypeField = ((string)(data));
    }
}
bool UnitValueAcquired = false;
if (this.Session.ContainsKey("Unit"))
{
    this._UnitField = ((string)(this.Session["Unit"]));
    UnitValueAcquired = true;
}
if ((UnitValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Unit");
    if ((data != null))
    {
        this._UnitField = ((string)(data));
    }
}
bool StartDateValueAcquired = false;
if (this.Session.ContainsKey("StartDate"))
{
    this._StartDateField = ((string)(this.Session["StartDate"]));
    StartDateValueAcquired = true;
}
if ((StartDateValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("StartDate");
    if ((data != null))
    {
        this._StartDateField = ((string)(data));
    }
}
bool EndDateValueAcquired = false;
if (this.Session.ContainsKey("EndDate"))
{
    this._EndDateField = ((string)(this.Session["EndDate"]));
    EndDateValueAcquired = true;
}
if ((EndDateValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EndDate");
    if ((data != null))
    {
        this._EndDateField = ((string)(data));
    }
}
bool CreatedOnValueAcquired = false;
if (this.Session.ContainsKey("CreatedOn"))
{
    this._CreatedOnField = ((string)(this.Session["CreatedOn"]));
    CreatedOnValueAcquired = true;
}
if ((CreatedOnValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("CreatedOn");
    if ((data != null))
    {
        this._CreatedOnField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class testingBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
